### ISSUE TITLE
Implement a way of using self account for bot. 

### ISSUE THREAD

**Issue by ethan-0l** [jykob/TSBot#47]
Hello. 

I got an issue located here : 
commands/handler.py in COmmandHandler 

```
    async def handle_command_event(self, bot: bot.TSBot, ctx: context.TSCtx) -> None:
        """Logic to handle commands"""
        print(f"invokeruid: {ctx.get('invokeruid')}, bot.uid: {bot.uid}")
        # If sender is the bot, return
        # if ctx.get("invokeruid") == bot.uid:
        #     return
```
The command registered didn't work with my own account 

Tried to monkey patch but since uid is updated in the run() func of the bot, it's not possible (or i'm not good enough for ^^) 

Suggestion : 
  if possible :  Allow in some way to differenciate bot instance from user instance. 
 Or 
  allow to disable invokeruid verification,  or update tu bot uid ? 
  
  Really like your work btw :)

**Comment by jykob** [comment]
Thanks!

`textmessage` events from the TeamSpeak server are fairly limited on what information it gives about the sender of the message.
These fields are: `invokerid`, `invokername`, `invokeruid`.

The check is there to prevent infinite loops.

The bot only checks for uids since those are static and wont change.
This why I advocate to create separate bot identity to be used.

Currently the bot's client id shouldn't change since there is no reconnect mechanism in place.
The bot could check uids and clids to determine if the message came from an actual user or from itself.

**Comment by jykob** [comment]
Meanwhile, if you want to disable uid check, you could set `bot.uid` to `""` for example in "ready" event handler.

```python
@bot.on("ready")
async def change_uid(bot: TSBot, ctx: TSCtx):
    bot.uid = ""
```
