### ISSUE TITLE
[question] slow poke query performance

### ISSUE THREAD

**Issue by matheusrps** [jykob/TSBot#67]
I've a simple command that pokes all user online:

```
clients = await bot.send(query("clientlist"))
logger.info("Starting clientpoke queries")

try:
    tasks = [bot.send(query("clientpoke").params(clid=client["clid"], msg=formatted_message))
             for client in clients if client["client_type"] == "0"]

    await asyncio.gather(*tasks)
except Exception as e:
    logger.error(f"Error poking clients: {e}")

logger.info(f"clientpoke queries completed took {time() - start_time:.2f} seconds")
```

Is there an option with increased performance? It's taking 20-30 seconds to complete.

**Comment by jykob** [comment]
I assume you don't have the bot configured to be ratelimited.

There is a technical reason why a bunch of queries can be slow. Due to the primitive nature of TeamSpeaks Server Query interface, each query sent has to get the response from the server. Even if you don't need it.

This also means each query has to wait for the ones that were sent before it. This ensures that the responses dont come back out-of-order.

So each query is a round trip from the bots location to the server and back, and they have to be sent one by one.

What is the ballpark amount of queries the bot is sending and latency between the bot and the server?

**Comment by matheusrps** [comment]
I've set when instantiating TSBot: username, password, nickname, address, por and protocol (raw) is it a good approach to tweak those:
```
        connection_retries: int = 3,
        connection_retry_timeout: float = 10,
        ratelimited: bool = False,
        ratelimit_calls: int = 10,
        ratelimit_period: float = 3,
        query_timeout: float = 5,
```

Also, usually I'm sending ~50 pokes.
And now I'm measuring how long each poke took to each client, it ranges from 0.213s to 3.368s why does it vary so much? Is there a way to improve this perfomance?

**Comment by jykob** [comment]
If the `TSBot` instance is configured with `ratelimited=False` (_the default behavior_), the bot will try to send queries as fast as it can.

That 3 seconds jumps out a bit. Maybe the TeamSpeak server is throttling the responses.

I am currently not able to do my own testing for a few days.

**Comment by jykob** [comment]
Did some testing.

Example command:
```python
@bot.command("flood", help_text="floods server with queries")
async def flood(bot: TSBot, ctx: TSCtx, clid: str):
    poke_query = query("clientpoke").params(clid=clid, msg="spam")
    start = time.monotonic()

    await asyncio.gather(*(bot.send(poke_query) for _ in range(50)))

    logger.debug("Flood took %.5f seconds", time.monotonic() - start)
```

While each query took ~0.015s to execute, this took about a second to completely execute on my machine with local TeamSpeak server.

The huge factor here is the latency between the bot and the server,
since each query has to be sent one-by-one. (_round trip to the server and back_)

Since your lowest measurement was 0.2s, I assume your bot instance isn't near the TeamSpeak server from a networking perspective.

---

> it ranges from 0.213s to 3.368s why does it vary so much?

It is pretty hard to measure the timing for each query because each query is queued with a lock.
Without diving into the internals, the time spent in queue is also added to the total time.
This would explain linearly increasing time between each query. (_Each query executing after one another_)

You can checkout [coro-timing](/jykob/tsbot/tree/coro-timing) branch (PR #68) to measure each query execution time.

**Comment by matheusrps** [comment]
It's working perfectly, I've managed to test it and it's working really well. I've changed plugin_exemple.py to include an example of a batched query. But I 've no access rights to push. Here's what I did, a fairly simple (`plugin_example.py`):

```python
from __future__ import annotations

import asyncio

from tsbot import TSBot, TSCtx, plugin, query


class TestPlugin(plugin.TSPlugin):
    def __init__(self) -> None:
        self.message = "Hello from plugin"
        self.move_message = "{username} has moved"

    @plugin.command("hello")
    async def plugin_hello(self, bot: TSBot, ctx: TSCtx):
        await bot.respond(ctx, message=self.message)

    @plugin.command("pokeall", raw=True)
    async def plugin_hello(self, bot: TSBot, ctx: TSCtx, message: str):
        clients = await bot.send(query("clientlist"))
        poke_query = query("clientpoke").params(msg=message)
        await bot.send_batched(
            poke_query.params(clid=client["clid"])
            for client in clients
            if client["client_type"] == "0"
        )

    @plugin.on("clientmoved")
    async def plugin_move(self, bot: TSBot, ctx: TSCtx):
        info_query = query("clientinfo").params(clid=ctx["clid"])
        resp = await bot.send(info_query)

        print(self.move_message.format(username=resp.first["client_nickname"]))


bot = TSBot(
    username="USERNAME",
    password="PASSWORD",
    address="ADDRESS",
)
bot.load_plugin(TestPlugin())

asyncio.run(bot.run())
```
